### ISSUE TITLE
youtube_dl_server doesn't work on Windows

### ISSUE THREAD

**Issue by lazarcf** [r4mos/youtube-dl-chrome-plugin#1]
I get this error from the server when I try to use the extension, seems youtube_dl_server isn't cross-platform. Might want to update your README.

> C:\Users\Claudiu> \* Running on http://localhost:9191/ (Press CTRL+C to quit)
> Traceback (most recent call last):
>   File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "C:\Python27\lib\runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "C:\Python27\lib\site-packages\youtube_dl_server__main__.py", line 6, in <module>
>     sys.exit(main())
>   File "C:\Python27\lib\site-packages\youtube_dl_server\server.py", line 48, in main
>     app.run(args.host, args.port, processes=args.number_processes)
>   File "C:\Python27\lib\site-packages\flask\app.py", line 843, in run
>     run_simple(host, port, self, **options)
>   File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 694, in run_simple
>     inner()
>   File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 659, in inner
>     srv.serve_forever()
>   File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 499, in serve_forever
>     HTTPServer.serve_forever(self)
>   File "C:\Python27\lib\SocketServer.py", line 233, in serve_forever
>     self._handle_request_noblock()
>   File "C:\Python27\lib\SocketServer.py", line 292, in _handle_request_noblock
>     self.handle_error(request, client_address)
>   File "C:\Python27\lib\SocketServer.py", line 290, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "C:\Python27\lib\SocketServer.py", line 559, in process_request
>     pid = os.fork()
> AttributeError: 'module' object has no attribute 'fork'

**Comment by r4mos** [comment]
It seems a problem related to [youtube-dl-api-server](https://github.com/jaimeMF/youtube-dl-api-server) but I would like to reproduce this error. What version of windows? How the server you have installed?

**Comment by r4mos** [comment]
Try running the server with the following command: `python -m youtube_dl_server --number-processes 1`

I think you can't use more than one process in Windows.

I will update README, thx
