### ISSUE TITLE
Audio merge

### ISSUE THREAD

**Issue by hjyoung1** [r4mos/youtube-dl-chrome-plugin#3]
Currently i get videos without audio.
Is it possible to merge both automatically using ffmpeg if it's available on my system.

**Comment by r4mos** [comment]
This plugin is only a GUI for youtube-dl-api-server so you should be able to download videos with audio. If you can't download the videos with audio, they weren't available on the server. Could you give me an example?

**Comment by hjyoung1** [comment]
Ah you're right. I got confused after reading this (https://github.com/jaimeMF/youtube-dl-api-server/issues/53)
But for default quality audio is present.
But for different quality (resolution) no audio in video. 
![Screenshot_20190528-030447](https://user-images.githubusercontent.com/45882061/58440673-4a1ae780-80f9-11e9-91f2-e29b4d32e101.png)
For this default resolution i get video with audio included.
But if i want better resolution like 1080p from more menu there's no audio. 
Example link :- https://youtu.be/rUWxSEwctFU

**Comment by r4mos** [comment]
ok, I close this issue
